#!/bin/bash

vitest run --coverage > ./coverage.json

passed=$(grep -Po '"numPassedTests":\d+' test_out.json | grep -Po '\d+')
total=$(grep -Po 'numTotalTests":\d+' test_out.json | grep -Po '\d+')

lines=$(grep -i 'All\sFiles' coverage.json | awk '{print $10}' | cut -d '.' -f 1)

echo "$passed/$total test cases passed. $lines% line coverage achieved."

exit 0